version: '3'
services:
  gha:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-actions
    privileged: true
    tty: true
    volumes:
      - ./workspace:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
